# -*- coding: utf-8 -*-
"""Asteroid Detection Hazard Risk Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ii6DDpMkuQ6pW0rFXCSBDyG5qL87oFmy
"""

#---------------------------------Data Analysis--------------------------------
!pip install pandas matplotlib seaborn

# STEP 1 — Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# STEP 2 — Upload Dataset
import pandas as pd
file_path = "/content/drive/MyDrive/neo_v2.csv.csv"
data = pd.read_csv(file_path)
print(data.head())

data.info()

data.describe()

# STEP 3 — Check Columns
data.columns

# STEP 4 — Data Cleaning
data = data.drop(columns=['Unnamed: 0'])

# STEP 5 — Hazardous Asteroid Detection
hazard_counts = data['is_potentially_hazardous_asteroid'].value_counts()

hazard_counts

# STEP 6 — Visualization 1
hazard_counts.plot(kind='bar')

plt.title("Hazardous vs Non-Hazardous Asteroids")
plt.xlabel("Hazard Status")
plt.ylabel("Number of Asteroids")
plt.show()

#STEP 7 — Asteroid Size Analysis
sns.histplot(data['kilometers_estimated_diameter_min'], bins=40)

plt.title("Asteroid Size Distribution")
plt.xlabel("Diameter (km)")
plt.show()

# STEP 8 — Orbit Type Analysis
plt.figure(figsize=(8,5))

data['orbit_class_type'].value_counts().plot(kind='bar')

plt.title("Asteroid Orbit Classes")
plt.show()

# STEP 9 — Hazard vs Size Relationship
sns.boxplot(
    x='is_potentially_hazardous_asteroid',
    y='kilometers_estimated_diameter_min',
    data=data
)

plt.title("Hazard vs Asteroid Size")
plt.show()

#STEP 10 : Visualization - Hazard Percentage Pie Chart
hazard_counts = data['is_potentially_hazardous_asteroid'].value_counts()

plt.figure(figsize=(6,6))

plt.pie(
    hazard_counts,
    labels=["Safe","Hazardous"],
    autopct='%1.1f%%',
    startangle=90
)

plt.title("Percentage of Hazardous Asteroids")
plt.show()

# Visualization — 3D Asteroid Risk Visualization
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(9,7))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(
    data['absolute_magnitude_h'],
    data['kilometers_estimated_diameter_min'],
    data['perihelion_distance'],
    c=data['is_potentially_hazardous_asteroid'].astype(int)
)

ax.set_xlabel("Brightness")
ax.set_ylabel("Diameter")
ax.set_zlabel("Perihelion Distance")

plt.title("3D Asteroid Risk Visualization")
plt.show()

# Visualization — Top Largest Asteroids Chart
top10 = data.nlargest(10,'kilometers_estimated_diameter_max')

plt.figure(figsize=(10,5))

sns.barplot(
    x='name',
    y='kilometers_estimated_diameter_max',
    data=top10
)

plt.xticks(rotation=90)
plt.title("Top 10 Largest Asteroids")
plt.show()

# Visualization — Box Plot
plt.figure(figsize=(8,5))

sns.boxplot(
    x='is_potentially_hazardous_asteroid',
    y='absolute_magnitude_h',
    data=data
)

plt.title("Hazard Level vs Asteroid Brightness")
plt.show()

# STEP 11 — Create Risk Label (Detection Logic)
def risk_label(x):
    if x == True:
        return "High Risk"
    else:
        return "Low Risk"

data["Risk_Level"] = data['is_potentially_hazardous_asteroid'].apply(risk_label)

data[['name','Risk_Level']].head()

#------------------------------------FOR ACCURACY (ML)-----------------------

#STEP 1 — Install ML Library (Colab)

!pip install scikit-learn

#STEP 2 — Import ML Libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#STEP 3 — Select Features
features = data[[
    'absolute_magnitude_h',
    'kilometers_estimated_diameter_min',
    'kilometers_estimated_diameter_max',
    'perihelion_distance',
    'aphelion_distance'
]]

target = data['is_potentially_hazardous_asteroid']

#STEP 4 — Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    features,
    target,
    test_size=0.2,
    random_state=42
)

#STEP 5 — Train Model
model =RandomForestClassifier()

model.fit(X_train, y_train)

#STEP 6 — Make Predictions
predictions = model.predict(X_test)

#STEP 7 — Calculate Accuracy
accuracy = accuracy_score(y_test, predictions)

print("Model Accuracy:", accuracy)

#STEP 8 — Confusion Matrix (Teacher Impressing)
confusion_matrix(y_test, predictions)

#Better Visualization

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(confusion_matrix(y_test, predictions),
            annot=True,
            fmt='d')

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# STEP 9 — Classification Report
print(classification_report(y_test, predictions))